In [1]:
# this notebook is perform anaylsis of MACE events in the care home hypertension cohort

In [2]:
library(ggplot2)
library(bigrquery)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(stats)

ProjectId = "yhcr-prd-bradfor-bia-core"

targetdb1 <-'yhcr-prd-bradfor-bia-core.CB_MYSPACE_MK'
targetdb1 <-gsub(' ','',targetdb1)

targetdb2 <- 'yhcr-prd-bradfor-bia-core.CB_FDM_DeathCertificates'
targetdb2 <-gsub(' ','',targetdb2)

targetdb3 <- 'yhcr-prd-bradfor-bia-core.CB_2172'
targetdb3 <- gsub(' ','',targetdb3)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [3]:
sql1 <- 
paste(
    'SELECT  *
from ',targetdb3,'.cb_2172_mace 
;',sep="")

mace_tbl <-bq_project_query(ProjectId,sql1)
mace_data <- bq_table_download(mace_tbl)
#filter out any individuals where the time between admission and death is less than 42 days

In [4]:
mace_data$date.event <- as.Date(mace_data$dod)

mace_data <- mace_data %>% select(-dod)

In [5]:
mace_data <- mace_data %>% arrange(person_id, desc(date.event)) %>% mutate(event_id= rank(date.event
                                                                                        ))
#here is the initial data, the problem is there are some  duplicate events where the data differs by only a couple of days so they are counted as different events. 
#Some cardiovasccular deaths also have  the cardiovascular event (e.g. myocardial evvent, recorded as a seperate event a few days apart). 
#I need to remove these events so that only the cardiovascular death is recorded. 
#This is based on the assumption that where a stroke or MI has been recorded within 30 days of a cardiovascular death, the two are realted and therefore the stroke or MI was a fatal one so should be recorded as a CV death rather than a non fatal MI or stroke. 
mace_data

    person_id event_type            date.event event_id
1     339912  cv death              2017-12-15  72.5
2     533373  cv death              2017-11-15  65.5
3     576388  cv death              2019-10-15 180.0
4     658432  cv death              2019-05-15 156.0
5     706765  cv death              2019-03-15 140.0
6     879366  cv death              2019-06-15 162.5
7     879366  myocardial infarction 2019-06-10 159.0
8     899131  myocardial infarction 2020-05-26 201.0
9     899131  cv death              2020-05-15 200.0
10  12388259  cv death              2017-02-15  16.5
11  12390501  cv death              2019-07-15 169.5
12  12394871  myocardial infarction 2019-03-15 140.0
13  12394871  myocardial infarction 2019-03-12 136.0
14  12398061  cv death              2018-09-15 109.5
15  12401518  stroke                2017-05-02  32.0
16  12402870  myocardial infarction 2017-10-26  62.0
17  12406005  cv death              2017-10-15  60.0
18  12407105  myocardial infarction 2018-03-06  87.5
19  12407105  cv death              2018-02-15  82.0
20  12415453  myocardial infarction 2017-06-24  46.0
21  12421727  cv death              2020-01-15 189.5
22  12427943  cv death              2019-05-15 156.0
23  12429242  stroke                2020-02-21 193.0
24  12429724  cv death              2019-11-15 184.0
25  12437211  cv death              2017-02-15  16.5
26  12441334  cv death              2017-06-15  41.0
27  12443495  cv death              2019-01-15 128.5
28  12449343  myocardial infarction 2019-02-28 134.0
29  12449857  cv death              2017-09-15  56.0
30  12451603  cv death              2020-04-15 199.0
⋮   ⋮         ⋮                     ⋮          ⋮
175 13565415  cv death              2018-02-15  82.0
176 13576861  stroke                2017-06-19  45.0
177 13576950  stroke                2020-03-28 198.0
178 13580091  cv death              2018-07-15 102.0
179 13580091  myocardial infarction 2018-05-07  96.0
180 13580202  myocardial infarction 2016-06-07   2.0
181 13580202  myocardial infarction 2016-06-06   1.0
182 13583345  stroke                2017-10-01  58.0
183 13586529  stroke                2019-02-08 130.0
184 13596832  stroke                2017-06-13  37.0
185 13600459  cv death              2017-07-15  48.0
186 13621165  myocardial infarction 2017-09-04  54.0
187 13622104  cv death              2018-12-15 124.5
188 13633332  cv death              2019-05-15 156.0
189 13638262  cv death              2017-06-15  41.0
190 13670902  myocardial infarction 2019-08-18 174.0
191 13676724  cv death              2018-11-15 119.5
192 13679402  cv death              2018-10-15 116.5
193 13679557  stroke                2018-12-06 122.0
194 13687907  cv death              2018-08-15 105.5
195 13688187  cv death              2018-04-15  93.0
196 13700374  cv death              2018-10-15 116.5
197 13706066  stroke                2017-03-27  26.0
198 13711038  cv death              2017-02-15  16.5
199 13712846  cv death              2017-12-15  72.5
200 13723011  cv death              2018-07-15 102.0
201 13723242  cv death              2017-04-15  30.0
202 13723242  stroke                2017-02-25  20.0
203 13730554  cv death              2017-01-15  12.0
204 13751806  stroke                2018-03-08  89.5

In [ ]:
# this identifies myocardial infarction events where another event occurs afterwards(either a duplicate event or death), so these myocardial events can be removed, i will do the same for stroke as well. this ensures only non fatal myocardial infarctions and strokes are captured in the MACE outcomes. fatal myocardial infarctions and stroke would fall into CV death 
mace_data_filtered_mi_cvd <- mace_data %>%
  group_by(person_id) %>% filter(event_type == 'myocardial infarction' & !((date.event - lag(date.event)) >= 30 & (date.event - lag(date.event)) > 0)) %>%
  ungroup() 

mace_data_filtered_mi_cvd

In [ ]:
mace_data

In [ ]:
mace_data <- mace_data %>% arrange(person_id, desc(date.event))


# this identifies stroke events where another event occurs afterwards(either a duplicate event or death), so these myocardial events can be removed, i will do the same for stroke as well. this ensures only non fatal myocardial infarctions and strokes are captured in the MACE outcomes. fatal myocardial infarctions and stroke would fall into CV death 
mace_filtered_stroke_cvd <- mace_data %>%
  group_by(person_id) %>% filter(event_type == 'stroke' & !((date.event - lag(date.event)) >= 30 & (date.event - lag(date.event)) > 0)) %>%
  ungroup() 

mace_filtered_stroke_cvd

In [9]:
#i then subsetted the mace_Data to remove those duplicate stroke and myocardial events identified above

In [10]:
#creat he not in function

'%notin%' <- Negate(`%in%`)

In [11]:
mace_data_filtered <- mace_data[mace_data$event_id %notin% mace_data_filtered_mi_cvd$event_id, ]

In [12]:
mace_data_filtered <- mace_data_filtered[mace_data_filtered$date.event %notin% mace_filtered_stroke_cvd$date.event, ]

In [16]:
mace_data_filtered <- mace_data_filtered %>% arrange(person_id, desc(date.event))

mace_data_filtered

    person_id event_type            date.event event_id
1     339912  cv death              2017-12-15  72.5
2     533373  cv death              2017-11-15  65.5
3     576388  cv death              2019-10-15 180.0
4     658432  cv death              2019-05-15 156.0
5     706765  cv death              2019-03-15 140.0
6     879366  cv death              2019-06-15 162.5
7     899131  myocardial infarction 2020-05-26 201.0
8     899131  cv death              2020-05-15 200.0
9   12388259  cv death              2017-02-15  16.5
10  12390501  cv death              2019-07-15 169.5
11  12394871  myocardial infarction 2019-03-15 140.0
12  12398061  cv death              2018-09-15 109.5
13  12401518  stroke                2017-05-02  32.0
14  12402870  myocardial infarction 2017-10-26  62.0
15  12406005  cv death              2017-10-15  60.0
16  12407105  myocardial infarction 2018-03-06  87.5
17  12407105  cv death              2018-02-15  82.0
18  12415453  myocardial infarction 2017-06-24  46.0
19  12421727  cv death              2020-01-15 189.5
20  12427943  cv death              2019-05-15 156.0
21  12429242  stroke                2020-02-21 193.0
22  12429724  cv death              2019-11-15 184.0
23  12437211  cv death              2017-02-15  16.5
24  12441334  cv death              2017-06-15  41.0
25  12443495  cv death              2019-01-15 128.5
26  12449343  myocardial infarction 2019-02-28 134.0
27  12449857  cv death              2017-09-15  56.0
28  12451603  cv death              2020-04-15 199.0
29  12455482  myocardial infarction 2016-12-05   7.0
30  12458587  myocardial infarction 2019-12-23 188.0
⋮   ⋮         ⋮                     ⋮          ⋮
163 13538264  cv death              2018-08-15 105.5
164 13542748  cv death              2017-06-15  41.0
165 13555576  stroke                2019-07-05 166.0
166 13565415  cv death              2018-02-15  82.0
167 13576861  stroke                2017-06-19  45.0
168 13576950  stroke                2020-03-28 198.0
169 13580091  cv death              2018-07-15 102.0
170 13580202  myocardial infarction 2016-06-07   2.0
171 13583345  stroke                2017-10-01  58.0
172 13586529  stroke                2019-02-08 130.0
173 13596832  stroke                2017-06-13  37.0
174 13600459  cv death              2017-07-15  48.0
175 13621165  myocardial infarction 2017-09-04  54.0
176 13622104  cv death              2018-12-15 124.5
177 13633332  cv death              2019-05-15 156.0
178 13638262  cv death              2017-06-15  41.0
179 13670902  myocardial infarction 2019-08-18 174.0
180 13676724  cv death              2018-11-15 119.5
181 13679402  cv death              2018-10-15 116.5
182 13679557  stroke                2018-12-06 122.0
183 13687907  cv death              2018-08-15 105.5
184 13688187  cv death              2018-04-15  93.0
185 13700374  cv death              2018-10-15 116.5
186 13706066  stroke                2017-03-27  26.0
187 13711038  cv death              2017-02-15  16.5
188 13712846  cv death              2017-12-15  72.5
189 13723011  cv death              2018-07-15 102.0
190 13723242  cv death              2017-04-15  30.0
191 13730554  cv death              2017-01-15  12.0
192 13751806  stroke                2018-03-08  89.5

In [ ]:
# merge the care home cohort table in order to calculate the incidence density

In [28]:
sql1 <- 
paste(
    'SELECT person_id,first_episodestartdate, hypertension
from ',targetdb3,'.cb_2172_hypertension_combined 
order by person_id
;',sep="")

bp_tbl <-bq_project_query(ProjectId,sql1)
ch_cohort <- bq_table_download(bp_tbl)

ch_cohort$person_id <- as.character(ch_cohort$person_id)
print(ch_cohort)

# A tibble: 2,794 × 3
   person_id first_episodestartdate hypertension
   <chr>     <dttm>                 <lgl>
 1 1271      2019-01-07 00:00:00    TRUE
 2 2355      2018-01-03 00:00:00    FALSE
 3 5275      2019-02-13 00:00:00    TRUE
 4 30746     2017-07-28 00:00:00    TRUE
 5 76037     2017-11-01 00:00:00    FALSE
 6 81564     2017-11-28 00:00:00    FALSE
 7 111197    2018-02-24 00:00:00    TRUE
 8 118634    2017-03-30 00:00:00    TRUE
 9 144752    2017-08-03 00:00:00    TRUE
10 158375    2018-03-26 00:00:00    TRUE
# ℹ 2,784 more rows

In [39]:
ch_mace_merged <- merge(x =ch_cohort, y = mace_data_filtered, all.x = TRUE)

In [40]:
ch_mace_merged$first_episodestartdate <- as_date(ch_mace_merged$first_episodestartdate)

In [41]:
ch_mace_merged <- ch_mace_merged %>% mutate(exposure_time = (date.event -first_episodestartdate))

In [42]:
 ch_mace_merged_filtered <- ch_mace_merged %>% filter(hypertension == TRUE)

In [43]:
ch_mace_merged_filtered$exposure_time <- ifelse(is.na(ch_mace_merged_filtered$exposure_time) ,365,ch_mace_merged_filtered$exposure_time)

In [46]:
ch_mace_merged_filtered <-ch_mace_merged_filtered %>%  select(-"event_id")

ERROR: Error in `select()`:
! Can't select columns that don't exist.
✖ Column `event_id` doesn't exist.

In [47]:
(sum(ch_mace_merged_filtered$exposure_time < 365)/(ch_mace_merged_filtered$exposure_time %>% sum()/365))*100

[1] 7.487116